# Generated by Django 5.2.1 on 2025-06-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_remove_event_vendor_code_alter_userprofile_role_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Connection",
        ),
    ]
