# Generated by Django 5.2.1 on 2025-06-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_delete_connection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="attendee_code",
            new_name="attendee_GA_code",
        ),
        migrations.AddField(
            model_name="event",
            name="attendee_VIP_code",
            field=models.CharField(default="VIP000", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="attendee_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
