# Generated by Django 5.2.1 on 2025-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_rename_attendee_code_event_attendee_ga_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendee_VIP_code",
            field=models.CharField(default="VIP000", max_length=10),
        ),
    ]
