# Generated by Django 5.2.1 on 2025-06-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_event_attendee_vip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendee_VIP_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
