# Generated by Django 5.2.1 on 2025-06-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_event_attendee_vip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendee_VIP_code",
            field=models.CharField(default="VIP123", max_length=10),
        ),
    ]
