# Generated by Django 5.2.1 on 2025-06-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_event_attendee_vip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="Event_ID",
            field=models.CharField(default="E_00", max_length=10),
        ),
    ]
