# Generated by Django 5.2.1 on 2025-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_event_event_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="Event_ID",
            new_name="event_ID",
        ),
        migrations.AddField(
            model_name="device",
            name="event_ID",
            field=models.CharField(default="E_00", max_length=10),
        ),
    ]
