# Generated by Django 5.2.1 on 2025-06-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_rename_event_id_event_event_id_device_event_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="event_ID",
            new_name="event_id",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_ID",
            new_name="event_id",
        ),
    ]
