# Generated by Django 5.2.1 on 2025-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_rename_event_id_device_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="event_id",
            field=models.CharField(default="E_00", max_length=10),
        ),
    ]
